Daraja Framework: TdjWebComponentHandler Class Reference
TdjWebComponentHandler Class Reference
Web Component handler.
Public Member Functions
TdjWebComponentHandler ()
Create a ContextHandler.
~TdjWebComponentHandler ()
Destructor.
AddMapping (const TdjWebComponentMapping Mapping)
Add a mapping.
AddWithMapping (const TdjWebComponentHolder Holder, const string PathSpec)
Add a Web Component holder with mapping.
TdjWebComponentHolder CreateHolder (const TdjWebComponentClass WebComponentClass)
Create a TdjWebComponentHolder for a WebComponentClass.
TdjWebComponentHolder FindHolder (const TdjWebComponentClass WebComponentClass)
Find a TdjWebComponentHolder for a WebComponentClass.
Handle (string Target, TdjServerContext Context, TdjRequest Request, TdjResponse Response)
Handle a HTTP request.
DoStart ()
Start the handler.
DoStop ()
Stop the handler.
Public Member Functions inherited from TdjAbstractHandler
TdjAbstractHandler ()
Constructor.
DoStart ()
Start the handler.
DoStop ()
Start the handler.
Handle (string Target, TdjServerContext Context, TdjRequest Request, TdjResponse Response)
Handle a HTTP request.
Public Member Functions inherited from TdjLifeCycle
TdjLifeCycle ()
Constructor.
Start ()
Start the handler.
Stop ()
Stop the handler.
Boolean IsStarted ()
Boolean IsStopped ()
Public Attributes
IContext WebComponentContext
TdjWebComponentMappings WebComponentMappings
TdjWebComponentHolders WebComponents
Public Attributes inherited from TdjLifeCycle
Boolean Started
True if the state is "started".
Boolean Stopped
True if the state is "stopped".
Protected Member Functions
TdjWebComponentHolder FindComponent (const string ATarget)
Find matching component.
Protected Member Functions inherited from TdjLifeCycle
DoStart ()
Execute the custom start code.
DoStop ()
Execute the custom stop code.
CheckStarted ()
Raises an exception if the lifecycle is in "started" state.
CheckStopped ()
Raises an exception if the lifecycle is in "stopped" state.
Detailed Description
Web Component handler.
An instance of this class is created per context.
It holds a list of web components and their path mappings, and passes incoming requests to the matching web component.
Constructor & Destructor Documentation
TdjWebComponentHandler()
TdjWebComponentHandler::TdjWebComponentHandler ()
Create a ContextHandler.
Use a ContextConfig (required argument) to configure the route mappings.
Member Function Documentation
AddWithMapping()
TdjWebComponentHandler::AddWithMapping (const TdjWebComponentHolder Holder, const string PathSpec)
Add a Web Component holder with mapping.
Parameters
Holder a Web Component holder
PathSpec a path spec
Referenced by TdjWebComponentContextHandler::Add(), and TdjWebComponentContextHandler::AddWebComponent().
CreateHolder()
TdjWebComponentHolder TdjWebComponentHandler::CreateHolder (const TdjWebComponentClass WebComponentClass)
Create a TdjWebComponentHolder for a WebComponentClass.
Parameters
WebComponentClass the Web Component class
Returns
a TdjWebComponentHolder with the WebComponentClass.
FindComponent()
TdjWebComponentHolder TdjWebComponentHandler::FindComponent (const string ATarget) protected
Find matching component.
Parameters
ATarget the URL document path.
FindHolder()
TdjWebComponentHolder TdjWebComponentHandler::FindHolder (const TdjWebComponentClass WebComponentClass)
Find a TdjWebComponentHolder for a WebComponentClass.
Parameters
WebComponentClass the Web Component class
Returns
a TdjWebComponentHolder with the WebComponentClass or nil if the WebComponentClass is not registered
Referenced by TdjWebComponentContextHandler::Add().
Handle()
TdjWebComponentHandler::Handle (string Target, TdjServerContext Context, TdjRequest Request, TdjResponse Response)
Handle a HTTP request.
Parameters
Target Request target
Context HTTP server context
Request HTTP request
Response HTTP response
Exceptions
EWebComponentException if an exception occurs that interferes with the component's normal operation
See also
IHandler
Referenced by TdjWebComponentContextHandler::DoHandle().
Member Data Documentation
WebComponentContext
IContext TdjWebComponentHandler::WebComponentContext
See also
FWebComponentContext For reading
WebComponentMappings
TdjWebComponentMappings TdjWebComponentHandler::WebComponentMappings
See also
FMappings For reading
WebComponents
TdjWebComponentHolders TdjWebComponentHandler::WebComponents
See also
FWebComponentHolders For reading